version: "3.8"
services:
    pg:
        container_name: postgres
        image: postgres:15.7-alpine
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: db
        ports:
            - "5432:5432"
        restart: no
        volumes:
            - ./postgres:/var/lib/postgresql/data
        networks:
            - note
    notion:
        container_name: notion
        image: carl/notion:v1.0.0
        environment:
            QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://47.97.28.82:5432/db
            QUARKUS_HTTP_CORS_ORIGINS: https://note-hffsr6019-michelleclars-projects.vercel.app
        ports:
            - "8080:8080"
        networks:
            - note

networks:
    note:
        driver: bridge