version: "3.8"
services:
  pg:
    container_name: postgres
    image: postgres:15.7-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    restart: no
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - note
  # mongo:
  #   image: "mongo:latest"
  #   container_name: mongodb
  #   ports:
  #     - "27018:27017"
  #   networks:
  #     - note
  notion:
    container_name: notion
    image: carl/notion:v1.0.0
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://pg:5432/db
    ports:
      - "8080:8080"
    networks:
      - note
  # pulsar:
  #   command: "bin/pulsar standalone"
  #   image: "apachepulsar/pulsar:latest"
  #   ports:
  #     - "9080:8080"
  #     - "6650:6650"
  #   tty: true
  #   stdin_open: true
  # consul:
  #   image: consul
  #   environment:
  #     - CONSUL_BIND_INTERFACE=eth1
  #   ports:
  #     - "8500:8500"
  #   container_name: consul
  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
  #   container_name: redis
  #   tty: true
  #   stdin_open: true
  #   networks:
  #     - note

networks:
  note:
    driver: bridge
